name: instagramclone
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  video_player: ^2.10.0
  get: ^4.7.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.14.4"
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # Assets added here
  assets:
    - assets/videos/
    - assets/images/
    - assets/icons/

# Use flutter_launcher_icons instead of deprecated flutter_icons
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/insta_new_logo.png"
